// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

// The realtime protocol for the template match engine.

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The marks available in the game.
type Mark int32

const (
	// No mark specified. Unused.
	Mark_MARK_UNSPECIFIED Mark = 0
	// X (Cross).
	Mark_MARK_X Mark = 1
	// O (Nought).
	Mark_MARK_O Mark = 2
)

var Mark_name = map[int32]string{
	0: "MARK_UNSPECIFIED",
	1: "MARK_X",
	2: "MARK_O",
}

var Mark_value = map[string]int32{
	"MARK_UNSPECIFIED": 0,
	"MARK_X":           1,
	"MARK_O":           2,
}

func (x Mark) String() string {
	return proto.EnumName(Mark_name, int32(x))
}

func (Mark) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

// The complete set of opcodes used for communication between clients and server.
type OpCode int32

const (
	// No opcode specified. Unused.
	OpCode_OPCODE_UNSPECIFIED OpCode = 0
	// New game round starting.
	OpCode_OPCODE_START OpCode = 1
	// Update to the state of an ongoing round.
	OpCode_OPCODE_UPDATE OpCode = 2
	// A game round has just completed.
	OpCode_OPCODE_DONE OpCode = 3
	// A move the player wishes to make and sends to the server.
	OpCode_OPCODE_MOVE OpCode = 4
	// Move was rejected.
	OpCode_OPCODE_REJECTED OpCode = 5
)

var OpCode_name = map[int32]string{
	0: "OPCODE_UNSPECIFIED",
	1: "OPCODE_START",
	2: "OPCODE_UPDATE",
	3: "OPCODE_DONE",
	4: "OPCODE_MOVE",
	5: "OPCODE_REJECTED",
}

var OpCode_value = map[string]int32{
	"OPCODE_UNSPECIFIED": 0,
	"OPCODE_START":       1,
	"OPCODE_UPDATE":      2,
	"OPCODE_DONE":        3,
	"OPCODE_MOVE":        4,
	"OPCODE_REJECTED":    5,
}

func (x OpCode) String() string {
	return proto.EnumName(OpCode_name, int32(x))
}

func (OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

// Message data sent by server to clients representing a new game round starting.
type Start struct {
	// The current state of the board.
	Board []Mark `protobuf:"varint,1,rep,packed,name=board,proto3,enum=api.Mark" json:"board,omitempty"`
	// The assignments of the marks to players for this round.
	Marks map[string]Mark `protobuf:"bytes,2,rep,name=marks,proto3" json:"marks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=api.Mark"`
	// Whose turn it is to play.
	Mark Mark `protobuf:"varint,3,opt,name=mark,proto3,enum=api.Mark" json:"mark,omitempty"`
	// The deadline time by which the player must submit their move, or forfeit.
	Deadline             int64    `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Start) Reset()         { *m = Start{} }
func (m *Start) String() string { return proto.CompactTextString(m) }
func (*Start) ProtoMessage()    {}
func (*Start) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Start) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Start.Unmarshal(m, b)
}
func (m *Start) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Start.Marshal(b, m, deterministic)
}
func (m *Start) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Start.Merge(m, src)
}
func (m *Start) XXX_Size() int {
	return xxx_messageInfo_Start.Size(m)
}
func (m *Start) XXX_DiscardUnknown() {
	xxx_messageInfo_Start.DiscardUnknown(m)
}

var xxx_messageInfo_Start proto.InternalMessageInfo

func (m *Start) GetBoard() []Mark {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *Start) GetMarks() map[string]Mark {
	if m != nil {
		return m.Marks
	}
	return nil
}

func (m *Start) GetMark() Mark {
	if m != nil {
		return m.Mark
	}
	return Mark_MARK_UNSPECIFIED
}

func (m *Start) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

// A game state update sent by the server to clients.
type Update struct {
	// The current state of the board.
	Board []Mark `protobuf:"varint,1,rep,packed,name=board,proto3,enum=api.Mark" json:"board,omitempty"`
	// Whose turn it is to play.
	Mark Mark `protobuf:"varint,2,opt,name=mark,proto3,enum=api.Mark" json:"mark,omitempty"`
	// The assignments of the marks to players for this round.
	Marks map[string]Mark `protobuf:"bytes,3,rep,name=marks,proto3" json:"marks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=api.Mark"`
	// The deadline time by which the player must submit their move, or forfeit.
	Deadline             int64    `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetBoard() []Mark {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *Update) GetMark() Mark {
	if m != nil {
		return m.Mark
	}
	return Mark_MARK_UNSPECIFIED
}

func (m *Update) GetMarks() map[string]Mark {
	if m != nil {
		return m.Marks
	}
	return nil
}

func (m *Update) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

// Complete game round with winner announcement.
type Done struct {
	// The current state of the board.
	Board []Mark `protobuf:"varint,1,rep,packed,name=board,proto3,enum=api.Mark" json:"board,omitempty"`
	// The final state of the board.
	Mark Mark `protobuf:"varint,2,opt,name=mark,proto3,enum=api.Mark" json:"mark,omitempty"`
	// The assignments of the marks to players for this round.
	Marks map[string]Mark `protobuf:"bytes,3,rep,name=marks,proto3" json:"marks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=api.Mark"`
	// The winner of the game, if any. Unspecified if it's a draw.
	Winner Mark `protobuf:"varint,4,opt,name=winner,proto3,enum=api.Mark" json:"winner,omitempty"`
	// Winner board positions, if any. Used to display the row, column, or diagonal that won the game.
	// May be empty if it's a draw or the winner is by forfeit.
	WinnerPositions []int32 `protobuf:"varint,5,rep,packed,name=winner_positions,json=winnerPositions,proto3" json:"winner_positions,omitempty"`
	// Next round start time.
	NextGameStart        int64    `protobuf:"varint,6,opt,name=next_game_start,json=nextGameStart,proto3" json:"next_game_start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Done) Reset()         { *m = Done{} }
func (m *Done) String() string { return proto.CompactTextString(m) }
func (*Done) ProtoMessage()    {}
func (*Done) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Done) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Done.Unmarshal(m, b)
}
func (m *Done) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Done.Marshal(b, m, deterministic)
}
func (m *Done) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Done.Merge(m, src)
}
func (m *Done) XXX_Size() int {
	return xxx_messageInfo_Done.Size(m)
}
func (m *Done) XXX_DiscardUnknown() {
	xxx_messageInfo_Done.DiscardUnknown(m)
}

var xxx_messageInfo_Done proto.InternalMessageInfo

func (m *Done) GetBoard() []Mark {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *Done) GetMark() Mark {
	if m != nil {
		return m.Mark
	}
	return Mark_MARK_UNSPECIFIED
}

func (m *Done) GetMarks() map[string]Mark {
	if m != nil {
		return m.Marks
	}
	return nil
}

func (m *Done) GetWinner() Mark {
	if m != nil {
		return m.Winner
	}
	return Mark_MARK_UNSPECIFIED
}

func (m *Done) GetWinnerPositions() []int32 {
	if m != nil {
		return m.WinnerPositions
	}
	return nil
}

func (m *Done) GetNextGameStart() int64 {
	if m != nil {
		return m.NextGameStart
	}
	return 0
}

// A player intends to make a move.
type Move struct {
	// The position the player wants to place their mark in.
	Position             int32    `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

// Payload for an RPC request to find a match.
type RpcFindMatchRequest struct {
	// User can choose a fast or normal speed match.
	Fast                 bool     `protobuf:"varint,1,opt,name=fast,proto3" json:"fast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcFindMatchRequest) Reset()         { *m = RpcFindMatchRequest{} }
func (m *RpcFindMatchRequest) String() string { return proto.CompactTextString(m) }
func (*RpcFindMatchRequest) ProtoMessage()    {}
func (*RpcFindMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *RpcFindMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcFindMatchRequest.Unmarshal(m, b)
}
func (m *RpcFindMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcFindMatchRequest.Marshal(b, m, deterministic)
}
func (m *RpcFindMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcFindMatchRequest.Merge(m, src)
}
func (m *RpcFindMatchRequest) XXX_Size() int {
	return xxx_messageInfo_RpcFindMatchRequest.Size(m)
}
func (m *RpcFindMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcFindMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RpcFindMatchRequest proto.InternalMessageInfo

func (m *RpcFindMatchRequest) GetFast() bool {
	if m != nil {
		return m.Fast
	}
	return false
}

// Payload for an RPC response containing match IDs the user can join.
type RpcFindMatchResponse struct {
	// One or more matches that fit the user's request.
	MatchIds             []string `protobuf:"bytes,1,rep,name=match_ids,json=matchIds,proto3" json:"match_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcFindMatchResponse) Reset()         { *m = RpcFindMatchResponse{} }
func (m *RpcFindMatchResponse) String() string { return proto.CompactTextString(m) }
func (*RpcFindMatchResponse) ProtoMessage()    {}
func (*RpcFindMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *RpcFindMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcFindMatchResponse.Unmarshal(m, b)
}
func (m *RpcFindMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcFindMatchResponse.Marshal(b, m, deterministic)
}
func (m *RpcFindMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcFindMatchResponse.Merge(m, src)
}
func (m *RpcFindMatchResponse) XXX_Size() int {
	return xxx_messageInfo_RpcFindMatchResponse.Size(m)
}
func (m *RpcFindMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcFindMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RpcFindMatchResponse proto.InternalMessageInfo

func (m *RpcFindMatchResponse) GetMatchIds() []string {
	if m != nil {
		return m.MatchIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Mark", Mark_name, Mark_value)
	proto.RegisterEnum("api.OpCode", OpCode_name, OpCode_value)
	proto.RegisterType((*Start)(nil), "api.Start")
	proto.RegisterMapType((map[string]Mark)(nil), "api.Start.MarksEntry")
	proto.RegisterType((*Update)(nil), "api.Update")
	proto.RegisterMapType((map[string]Mark)(nil), "api.Update.MarksEntry")
	proto.RegisterType((*Done)(nil), "api.Done")
	proto.RegisterMapType((map[string]Mark)(nil), "api.Done.MarksEntry")
	proto.RegisterType((*Move)(nil), "api.Move")
	proto.RegisterType((*RpcFindMatchRequest)(nil), "api.RpcFindMatchRequest")
	proto.RegisterType((*RpcFindMatchResponse)(nil), "api.RpcFindMatchResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x5f, 0x6f, 0x12, 0x4d,
	0x14, 0xc6, 0xdf, 0xfd, 0x1b, 0x38, 0x7d, 0x2b, 0xe3, 0x14, 0x9b, 0x4d, 0x8d, 0x71, 0xe5, 0xc2,
	0x50, 0xb4, 0x10, 0x8b, 0x17, 0xc6, 0x3b, 0x64, 0xb7, 0x06, 0x0d, 0x5d, 0x32, 0x50, 0x63, 0xbc,
	0x21, 0x03, 0x3b, 0x96, 0x15, 0x76, 0x67, 0xdd, 0x19, 0xaa, 0x4d, 0xfc, 0x4a, 0x7e, 0x1c, 0xe3,
	0xd7, 0x31, 0x3b, 0x0b, 0x28, 0x0d, 0x89, 0x17, 0xea, 0xdd, 0x99, 0xdf, 0x79, 0xe6, 0xc9, 0x79,
	0x66, 0x26, 0x03, 0x65, 0x9a, 0x46, 0xcd, 0x34, 0xe3, 0x92, 0x63, 0x83, 0xa6, 0x51, 0xed, 0x9b,
	0x06, 0xd6, 0x50, 0xd2, 0x4c, 0xe2, 0xfb, 0x60, 0x4d, 0x38, 0xcd, 0x42, 0x47, 0x73, 0x8d, 0xfa,
	0xad, 0xd3, 0x72, 0x33, 0x57, 0xf6, 0x69, 0x36, 0x27, 0x05, 0xc7, 0x8f, 0xc0, 0x8a, 0x69, 0x36,
	0x17, 0x8e, 0xee, 0x1a, 0xf5, 0xbd, 0xd3, 0x3b, 0x4a, 0xa0, 0xf6, 0x2a, 0x99, 0xf0, 0x13, 0x99,
	0x5d, 0x93, 0x42, 0x83, 0xef, 0x81, 0x99, 0x17, 0x8e, 0xe1, 0x6a, 0xdb, 0x66, 0x0a, 0xe3, 0x23,
	0x28, 0x85, 0x8c, 0x86, 0x8b, 0x28, 0x61, 0x8e, 0xe9, 0x6a, 0x75, 0x83, 0x6c, 0xd6, 0x47, 0x5d,
	0x80, 0x9f, 0x7e, 0x18, 0x81, 0x31, 0x67, 0xd7, 0x8e, 0xe6, 0x6a, 0xf5, 0x32, 0xc9, 0xcb, 0x7c,
	0xd0, 0x2b, 0xba, 0x58, 0x32, 0x47, 0xbf, 0xe9, 0x5d, 0xf0, 0xe7, 0xfa, 0x33, 0xad, 0xf6, 0x5d,
	0x03, 0xfb, 0x22, 0x0d, 0xa9, 0x64, 0xbf, 0x0f, 0xb6, 0x9e, 0x55, 0xdf, 0x3d, 0xeb, 0xe3, 0x75,
	0x6e, 0x43, 0xe5, 0x3e, 0x54, 0xfd, 0xc2, 0x7b, 0x47, 0xf0, 0x7f, 0x9e, 0xec, 0xab, 0x0e, 0xa6,
	0xc7, 0x93, 0x3f, 0xcf, 0xd5, 0xd8, 0xce, 0x55, 0x55, 0xfd, 0xdc, 0x79, 0x47, 0xaa, 0x07, 0x60,
	0x7f, 0x8a, 0x92, 0x84, 0x65, 0x2a, 0xd3, 0x96, 0xd9, 0xaa, 0x81, 0x8f, 0x01, 0x15, 0xd5, 0x38,
	0xe5, 0x22, 0x92, 0x11, 0x4f, 0x84, 0x63, 0xb9, 0x46, 0xdd, 0x22, 0x95, 0x82, 0x0f, 0xd6, 0x18,
	0x3f, 0x84, 0x4a, 0xc2, 0x3e, 0xcb, 0xf1, 0x25, 0x8d, 0xd9, 0x58, 0xe4, 0x2f, 0xc8, 0xb1, 0xd5,
	0x51, 0xed, 0xe7, 0xf8, 0x25, 0x8d, 0x99, 0x7a, 0x56, 0x7f, 0xe7, 0xbc, 0x6a, 0x60, 0xf6, 0xf9,
	0x15, 0xcb, 0x2f, 0x66, 0x3d, 0x98, 0xf2, 0xb0, 0xc8, 0x66, 0x5d, 0x3b, 0x86, 0x03, 0x92, 0x4e,
	0xcf, 0xa2, 0x24, 0xec, 0x53, 0x39, 0x9d, 0x11, 0xf6, 0x71, 0xc9, 0x84, 0xc4, 0x18, 0xcc, 0xf7,
	0x54, 0x48, 0x25, 0x2f, 0x11, 0x55, 0xd7, 0xda, 0x50, 0xdd, 0x96, 0x8a, 0x94, 0x27, 0x82, 0xe1,
	0xbb, 0x50, 0x8e, 0x73, 0x30, 0x8e, 0x42, 0xa1, 0x6e, 0xa4, 0x4c, 0x4a, 0x0a, 0xf4, 0x42, 0xd1,
	0x78, 0x0a, 0x66, 0x3e, 0x16, 0xae, 0x02, 0xea, 0x77, 0xc8, 0xeb, 0xf1, 0xc5, 0xf9, 0x70, 0xe0,
	0x77, 0x7b, 0x67, 0x3d, 0xdf, 0x43, 0xff, 0x61, 0x00, 0x5b, 0xd1, 0xb7, 0x48, 0xdb, 0xd4, 0x01,
	0xd2, 0x1b, 0x5f, 0xc0, 0x0e, 0xd2, 0x2e, 0x0f, 0x19, 0x3e, 0x04, 0x1c, 0x0c, 0xba, 0x81, 0xe7,
	0xdf, 0xd8, 0x89, 0xe0, 0xff, 0x15, 0x1f, 0x8e, 0x3a, 0x64, 0x84, 0x34, 0x7c, 0x1b, 0xf6, 0xd7,
	0xca, 0x81, 0xd7, 0x19, 0xf9, 0x48, 0xc7, 0x15, 0xd8, 0x5b, 0x21, 0x2f, 0x38, 0xf7, 0x91, 0xf1,
	0x0b, 0xe8, 0x07, 0x6f, 0x7c, 0x64, 0xe2, 0x03, 0xa8, 0xac, 0x00, 0xf1, 0x5f, 0xf9, 0xdd, 0x91,
	0xef, 0x21, 0xeb, 0x45, 0xfb, 0xdd, 0x93, 0xcb, 0x48, 0xce, 0x96, 0x93, 0xe6, 0x94, 0xc7, 0xad,
	0x19, 0xcb, 0x78, 0x34, 0x5d, 0xd0, 0x89, 0x68, 0x25, 0x74, 0x4e, 0x63, 0x7a, 0x92, 0x66, 0xfc,
	0x03, 0x9b, 0xca, 0x13, 0xc9, 0xe2, 0x74, 0x41, 0x25, 0x6b, 0xd1, 0x34, 0x9a, 0xd8, 0xea, 0x6b,
	0x69, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xef, 0x4d, 0x53, 0x67, 0x04, 0x00, 0x00,
}
